some corrections on install files - part 1
CAMAP-APP/camap-docker pull request #7
Opened 2024-05-15 09:43 UTC by Johbrun

Reste à traiter ce commentaire https://github.com/Mandrak-Kimigo/camap-docker/pull/5#discussion_r1601015852 , pour bien préparer les modes dev et non-dev

2024-05-15 16:02 UTC, Mandrak-Kimigo commented on camap-hx.Dockerfile
Je ne comprends pas toute les modifs de ce fichier, je suis preneur d'explications

- camap-hx/backend/  et camap-hx/frontend/ ne sont plus recopiés dans /srv dans le container

sont-ils inutiles au fonctionnement de l'appli haxe ?

- on ne copie plus config.xml et config-raw.xml dans /srv

comment est passé la config de camap-hx ? 

Si j'ai bien suivi, à l'origine on utilisait le raw et le script perl lancé au démarage générait le config.xml à partir du raw. Le script perl ne fonctionnant plus faute de variable d'environnement bien positionnées, il est désactivé, on n'en a plus besoin. Du coup le config-raw ne sert à rien non plus. 

Jusque là je suis, mais du coup: 
- comment est passé la conf puisqu'on ne copie plus non plus le config.xml ?
- doit on garder l'appel du start.sh dans CMD ? ne devrait-on pas directement lancer apache via /usr/sbin/apache2ctl -D FOREGROUND ? ou au moins supprimer le passage des arguments config-raw.xml et config.xml qui ne servent plus à rien car non traités par start.sh ?

Du coup j'ai remis le nez dans la doc docker et je me demande également si on ne devrait pas utiliser ENTRYPOINT au lieu de CMD ?

Voila dsl ça fait pas mal de questions mais je suis largué là

2024-05-19 18:43 UTC, Mandrak-Kimigo requested changes

2024-05-19 18:43 UTC, Mandrak-Kimigo commented on camap-hx.Dockerfile
> +COPY ./camap-hx/config.xml config-raw.xml
A supprimer

2024-05-19 18:43 UTC, Mandrak-Kimigo commented on camap-hx.Dockerfile
> -COPY --chown=www-data:www-data ./camap-hx/backend/ /srv/backend/
A remettre

2024-05-19 18:43 UTC, Mandrak-Kimigo commented on camap-hx.Dockerfile
> -COPY --chown=www-data:www-data ./camap-hx/frontend/ /srv/frontend/
A remettre

2024-05-19 18:43 UTC, Mandrak-Kimigo commented on camap-hx.Dockerfile
> -COPY ./camap-hx/config.xml /srv/config.xml
A remettre

2024-05-19 18:43 UTC, Mandrak-Kimigo commented on camap-hx.Dockerfile
> +CMD ["bash", "scripts/start.sh", "config-raw.xml", "config.xml" ]
Supprimer 
`CMD ["bash", "scripts/start.sh", "config-raw.xml", "config.xml" ]` 
et remplacer par:
`ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]`

2024-05-21 14:39 UTC, Lythom commented on camap-hx.Dockerfile
Vu ensemble :
- camap-hx/backend/ et camap-hx/frontend/ sont bien nécessaires. je les remet
- config.xml sert à exposer au runtime haxe les variables d'environnement. Nécessaire seulement si on déploie depuis un dépot vers un provider, on préfèrera supprimer le script pour simplifier pour le moment. Les personnes voulant déployer camap sur leur propre serveur devront soit :
  - monter le fichier via volume docker -v ./camap-hx/config.xml:/srv/config.xml s'ils utilisent docker
  - OU comme interamap44, configurer config.xml et rebuild leur l'image docker dans leur environnement
  - ne pas utiliser docker et utiliser la surcharge de leur choix pour modifier ce fichier de configuration.
- ENTRYPOINT à utiliser au lieu de CMD (sans le script)

2024-05-21 14:54 UTC, Mandrak-Kimigo approved these changes

2024-05-21 14:54 UTC, merged